name: Ruby Test

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'examples/ruby/**'
      - '.github/json2vars-setter/ruby_test.yml'

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.json2vars.outputs.os }}
      versions_ruby: ${{ steps.json2vars.outputs.versions_ruby }}
      ghpages_branch: ${{ steps.json2vars.outputs.ghpages_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Set variables from JSON
        id: json2vars
        uses: 7rikazhexde/json2vars-setter@v1.0.2
        with:
          json-file: examples/ruby/ruby_project_matrix.json

      - name: Debug output values
        run: |
          echo "os: ${{ steps.json2vars.outputs.os }}"
          echo "os[0]: ${{ fromJson(steps.json2vars.outputs.os)[0] }}"
          echo "os[1]: ${{ fromJson(steps.json2vars.outputs.os)[1] }}"
          echo "os[2]: ${{ fromJson(steps.json2vars.outputs.os)[2] }}"
          echo "versions_ruby: ${{ steps.json2vars.outputs.versions_ruby }}"
          echo "versions_ruby[0]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[0] }}"
          echo "versions_ruby[1]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[1] }}"
          echo "versions_ruby[2]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[2] }}"
          echo "versions_ruby[3]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[3] }}"
          echo "versions_ruby[4]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[4] }}"
          echo "versions_ruby[5]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[5] }}"
          echo "versions_ruby[6]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[6] }}"
          echo "versions_ruby[7]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[7] }}"
          echo "versions_ruby[8]: ${{ fromJson(steps.json2vars.outputs.versions_ruby)[8] }}"
          echo "ghpages_branch: ${{ steps.json2vars.outputs.ghpages_branch }}"

  run_tests:
    needs: set_variables
    strategy:
      matrix:
        os: ${{ fromJson(needs.set_variables.outputs.os) }}
        ruby-version: ${{ fromJson(needs.set_variables.outputs.versions_ruby) }}
        exclude:
          - os: windows-latest
            ruby-version: '3.4.0'
    runs-on: ${{ matrix.os }}
    outputs:
      test_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.276.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: './examples/ruby'

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Display Ruby version
        run: |
          ruby --version
          bundle --version

      - name: Show matrix
        shell: bash
        run: |
          # For non-list case
          ghpages_branch="${{ needs.set_variables.outputs.ghpages_branch }}"

          # For list case, explicitly enclose the list in "" to make it a string. (Note that it is not ''.)
          os='${{ needs.set_variables.outputs.os }}'
          versions_ruby='${{ needs.set_variables.outputs.versions_ruby }}'

          # For list index case
          os_0="${{ fromJson(needs.set_variables.outputs.os)[0] }}"
          os_1="${{ fromJson(needs.set_variables.outputs.os)[1] }}"
          os_2="${{ fromJson(needs.set_variables.outputs.os)[2] }}"

          versions_ruby_0="${{ fromJson(needs.set_variables.outputs.versions_ruby)[0] }}"
          versions_ruby_1="${{ fromJson(needs.set_variables.outputs.versions_ruby)[1] }}"
          versions_ruby_2="${{ fromJson(needs.set_variables.outputs.versions_ruby)[2] }}"
          versions_ruby_3="${{ fromJson(needs.set_variables.outputs.versions_ruby)[3] }}"
          versions_ruby_4="${{ fromJson(needs.set_variables.outputs.versions_ruby)[4] }}"
          versions_ruby_5="${{ fromJson(needs.set_variables.outputs.versions_ruby)[5] }}"
          versions_ruby_6="${{ fromJson(needs.set_variables.outputs.versions_ruby)[6] }}"
          versions_ruby_7="${{ fromJson(needs.set_variables.outputs.versions_ruby)[7] }}"
          versions_ruby_8="${{ fromJson(needs.set_variables.outputs.versions_ruby)[8] }}"

          echo "os: ${os}"
          echo "os_0: ${os_0}"
          echo "os_1: ${os_1}"
          echo "os_2: ${os_2}"
          echo "versions_ruby: ${versions_ruby}"
          echo "versions_ruby_0: ${versions_ruby_0}"
          echo "versions_ruby_1: ${versions_ruby_1}"
          echo "versions_ruby_2: ${versions_ruby_2}"
          echo "versions_ruby_3: ${versions_ruby_3}"
          echo "versions_ruby_4: ${versions_ruby_4}"
          echo "versions_ruby_5: ${versions_ruby_5}"
          echo "versions_ruby_6: ${versions_ruby_6}"
          echo "versions_ruby_7: ${versions_ruby_7}"
          echo "versions_ruby_8: ${versions_ruby_8}"
          echo "ghpages_branch: ${ghpages_branch}"

          # For loop case
          os_list=$(echo "${os}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
          ruby_versions_list=$(echo "${versions_ruby}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')

          for current_os in ${os_list}; do
            for version in ${ruby_versions_list}; do
              echo "Current OS: ${current_os}, Current Ruby Version: ${version}"
            done
          done

      - name: Run tests
        id: ruby_test
        working-directory: ./examples/ruby
        continue-on-error: true
        shell: bash
        run: |
          bundle install
          output="$(bundle exec rake test)"
          echo "${output}"

      - name: Set test status
        id: set_status
        if: always()
        shell: bash
        run: |
          if [ "${{ job.status }}" == "cancelled" ]; then
            echo "status=cancelled" >> "$GITHUB_OUTPUT"
          elif [ "${{ job.status }}" == "skipped" ]; then
            echo "status=skipped" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.ruby_test.outcome }}" == "failure" ]; then
            echo "status=failing" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.ruby_test.outcome }}" == "success" ]; then
            echo "status=passing" >> "$GITHUB_OUTPUT"
          else
            echo "status=pending" >> "$GITHUB_OUTPUT"
          fi

  update_badge:
    needs: run_tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set color
        id: set_color
        shell: bash
        run: |
          status="${{ needs.run_tests.outputs.test_status }}"
          if [ "$status" == "passing" ]; then
            echo "color=2ea44f" >> "$GITHUB_OUTPUT"
          elif [ "$status" == "failing" ]; then
            echo "color=cf222e" >> "$GITHUB_OUTPUT"
          elif [ "$status" == "pending" ]; then
            echo "color=dbab09" >> "$GITHUB_OUTPUT"
          else
            echo "color=808080" >> "$GITHUB_OUTPUT"
          fi

      - name: Create badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 511ba5b5711e66c507292ba00cf0a219
          filename: ruby-test-badge.json
          label: Ruby Test
          message: ${{ needs.run_tests.outputs.test_status }}
          color: ${{ steps.set_color.outputs.color }}
          labelColor: "24292f"
          style: "flat"
          namedLogo: "github"
          logoColor: "white"
